### ISSUE TITLE
Cannot find supervisord.conf when running the container

### ISSUE THREAD

**Issue by ChopsMcGee** [jdeathe/centos-ssh-apache-php#19]
I've been looking at both this image and the mysql images that you've put together, and I'm trying to evaluate whether I could build upon them when creating a redmine image. But when running the build.sh script and then the run.sh script, the container stops running and the container logs indicate that when it tried to run /usr/bin/supervisord --configuration=/etc/supervisord.conf it could not find the conf file. The confusing thing is, if I start up a container running the bash shell off of that same image, I can verify that /etc/supervisord.conf does in fact exist. Do you have any insight into why this error is occurring for me?

**Comment by jdeathe** [comment]
I have not been able to reproduce this. There could be some issue between the docker host system and the data volume container or between the data volume container and the app container. Most likely is a permissions issue on the Docker host preventing the configuration file being read on the container. 

When you run up your container to test I suspect you are not using the data volume so the configuration files will be the ones that are from within the container and not the ones mapped from the docker host to the container via the data volume. 

If you were following the manual instructions from the [README.md](https://github.com/jdeathe/centos-ssh-apache-php#optional-configuration-data-volume) before using the helper scripts and are on a Mac docker host you might have issues with the data volume due to issues with write access to /etc on Mac. I updated the run.conf to handle this case but the examples don't mention anything about it sorry. 

You shouldn't need to run the build.sh unless you are making changes to the Dockerfile so you could try and reset everything as follows:

1. Ensure you have the latest release code; the master branch is used for development and the centos-6 branch is the production code.

    ```
    $  git checkout centos-6 && git pull -p
    ```

2. stop and remove the app container and data volume.

    ```
    $ docker stop apache-php.app-1.1.1 && \
      docker rm apache-php.app-1.1.1  && \
      docker rm volume-config.apache-php.app-1.1.1
    ```

3. Backup/Remove the services-config and services-data the location of which depends on your docker host.

    3.1. For Darwin (Mac) hosts via boot2docker run:

    ```
    $ mv ~/services-config/apache-php.app-1.1.1 ~/services-config/apache-php.app-1.1.1.backup
    $ mv ~/services-data/apache-php/app-1 ~/services-data/apache-php/app-1.backup
    ```

    3.2. For CoreOS (or any other) docker hosts run:

    ```
    $ mv /etc/services-config/apache-php.app-1.1.1 /etc/services-config/apache-php.app-1.1.1.backup
    $ mv /var/services-data/apache-php/app-1 /var/services-data/apache-php/app-1.backup
    ```
4. Now you should be in a state where using the helper script will create a data volume and running container.

    ```
    $ bash run.sh
    ```

**Comment by jdeathe** [comment]
@ChopsMcGee - I have been able to reproduce this issue on CoreOS. 

Ref: https://github.com/jdeathe/centos-ssh-apache-php/blob/1.3.0/run.sh#L82

On CoreOS The helper script is copying the supervisor directory into the destination path instead of it's contents so we end up with for following path:
/etc/services-config/apache-php.app-1.1.1/supervisor/supervisor/supervisord.conf

What we are expecting is:
/etc/services-config/apache-php.app-1.1.1/supervisor/supervisord.conf

**Comment by jdeathe** [comment]
Ref: https://github.com/jdeathe/centos-ssh-apache-php/pull/20

**Comment by jdeathe** [comment]
Might need to re-open this issue:

```
docker logs mysql.pool-1.1.1
Error: could not find config file /etc/supervisord.conf
For help, use /usr/bin/supervisord -h
```

This issue can occur if there is some issue reading the files from the configurations loaded via:

```
--volumes-from volume-config.mysql.pool-1.1.1
```

To verify if the file is in place you can use the run.sh helper script to cat it's contents:

```
./run.sh cat /etc/supervisord.conf
```

When there is an issue reading the file from the configuration volume you will see the following error message:

```
cat: /etc/supervisord.conf: No such file or directory
```

**Comment by jdeathe** [comment]
This issue can occur when there is an issue with reading configuration volume files from a host operating environment or an issue reading the data from the configuration volume when using volumes-from on the running container.

Example:

```
docker logs <container-name>
Error: could not find config file /etc/supervisord.conf
For help, use /usr/bin/supervisord -h
```

This issue can occur if there is some issue reading the files from the configurations loaded via:

```
--volumes-from volume-config.<container-name>
```

To verify if the file is in place you can use the run.sh helper script to cat it's contents:

```
./run.sh cat /etc/supervisord.conf
```

When there is an issue reading the file from the configuration volume you will see the following error message:

```
cat: /etc/supervisord.conf: No such file or directory
```

**Comment by jdeathe** [comment]
The default VM created by boot2docker or docker tools and Kitematic automatically creates the shared directory for /Users so using paths such as ~/services-data when setting up the configuration volumes works. If you use an alternative Docker host VM and run docker commands from an OSX machine you will need to create the correct Synced directories. 

When running the run.sh helper scripts directly on the docker host it is currently assumed that the configuration data will be stored in /etc/services-config and the data will be stored in /var/services-data
