### ISSUE TITLE
Upgrading to PHP 5.4

### ISSUE THREAD

**Issue by MatthewHerbst** [jdeathe/centos-ssh-apache-php#89]
First off, awesome awesome repo - I've learned so much just by reading through the Dockerfile and figuring out what each `sed` is doing/why.

I'm interested in using the image as the base for another image I'm making, however, with PHP 5.4. If that's the only change I wanted to make, would you suggest forking and changing this repo or just upgrading in my own Dockerfile?

Also, would you be open to a pr that allowed specifying the PHP version?

**Comment by jdeathe** [comment]
PHP version as an option is in the pipeline but after I have got the FCGI
feature done so I can reduce the overhead of the seperate image I have for
that. I don't think it's a big deal to switch to an alternative PHP version
as it already has the IUS repository included from the source image. I am
working on 1.5.0 release of the base image currently which will also add
the SCL repository which is more in line with how RedHat does the
alternative PHP versions. Using IUS the php packages are named with the
php54u prefix.

If you want to do your own thing then it's no problem forking mine and
changing it to suit your needs. If you want to keep in line with my image
tags then use it as a source image and use specific tags rather than
:latest. You can see how I have done this by referencing the
jdeathe/centos-ssh-apache-php-fcgi repository and Dockerfile.

The fcgid php-wrapper actually already has a way to handle alternative php
versions by passing a parameter in the VirtualHosts file but the method
used requires the SCL repository. That should be fine for PHP 5.4 and 5.5.
They added 5.6 now too but when I wrote the php-wrapper it wasn't available.

So the simplest method for you would be to use the fcgi version as your
base image and add the scl repository to it then you can remove those steps
later after centos-ssh 1.5.0 gets tagged and I start back on the apache
images.

**Comment by MatthewHerbst** [comment]
Sounds good, thanks!
